website/transcriptions/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from flask_login import current_user
from wtforms.fields import StringField, PasswordField, SubmitField, BooleanField, TextAreaField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from website.models import User
            
class SaveWTranscriptionForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=3, max=100)])
    content = TextAreaField("Content", validators=[DataRequired()])
    submit = SubmitField('Save')

class SaveDTranscriptionForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=3, max=100)])
    content = TextAreaField("Content", validators=[DataRequired()])
    submit = SubmitField('Save')


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

website/main/routes.py
from flask import Blueprint
from flask import (render_template, redirect, url_for, 
                   flash, request, Blueprint)
from flask_login import login_required
import os
import time
import whisper_audio_formatter
import deepspeech_audio_formatter
import whisper_transcriber
import deepspeech_transcriber
import ray
from threading import *

main = Blueprint('main', __name__)

APP__ROOT = os.path.dirname(os.path.abspath(__name__))
ALLOWED_EXTENSIONS = {'mp3', 'mp4', 'wav'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

def delete_transcriptions():
    path_to_whisper_t = os.path.join(APP__ROOT, 'whisper_transcription/')
    for file in os.listdir(path_to_whisper_t):
        os.remove(f'{path_to_whisper_t}{file}')
    path_to_deepspeech_t = os.path.join(APP__ROOT, 'deepspeech_transcription/')
    for file in os.listdir(path_to_deepspeech_t):
        os.remove(f'{path_to_deepspeech_t}{file}')

@main.route("/", methods=["GET", "POST"])
@main.route("/home", methods=["GET", "POST"])
@login_required
def home():
    if request.method == 'POST':
        file = request.files['file']
        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)
        if file and allowed_file(file.filename):
            print("Got request in static files")
            target = os.path.join(APP__ROOT, "unformatted_audio/")

            if not os.path.isdir(target):
                os.mkdir(target)

            whisper_transcriber.delete_files()

            for file in request.files.getlist("file"):
                print(file)
                filename = file.filename
                destination = "/".join([target, filename])
                file.save(destination)

            delete_transcriptions()

            time.sleep(1)
            whisper_audio_formatter.audioFormatter()
            deepspeech_audio_formatter.main()
            
            dir_path = os.getcwd()


            def whisper_t():
                print("starting whisper")
                whisper_transcriber.main()
                whisper_transcription_path = f"{dir_path}/whisper_transcription/"
                for item in os.listdir(whisper_transcription_path):
                    if item.endswith('.txt'):
                        with open(str(whisper_transcription_path + item), "r") as f:
                            whisper_text = f.read()
                return whisper_text

            def deepspeech_t():
                deepspeech_transcriber.main()
                deepspeech_transcription_path = f'{dir_path}/deepspeech_transcription/'
                for item in os.listdir(deepspeech_transcription_path):
                    if item.endswith('.txt'):
                        with open(str(deepspeech_transcription_path + item), 'r') as g:
                            deepspeech_text = g.read()
                return deepspeech_text

            t1 = Thread(target=whisper_t)
            t2 = Thread(target=deepspeech_t)

            t1.start()
            t2.start()

            t1.join()
            t2.join()

            return redirect(url_for('transcripts.transcriptions', f_name=filename))
    return render_template("index2.html")

@main.route("/about")
def about():
    return render_template("about.html")

website/transcriptions/routes.py
from flask import (render_template, redirect, url_for, 
                   flash, request, abort, current_app, Blueprint)
from flask_login import current_user, login_required
from website.transcriptions.forms import SaveWTranscriptionForm, SaveDTranscriptionForm, PostForm
from website.models import User, Transcripts, Post
from website import db, share
import os

transcripts = Blueprint('transcripts', __name__)

@transcripts.route("/account/transcripts", methods=['GET', 'POST'])
@login_required
def account_transcripts():
    image_file = url_for('static', filename=f'profile_pics/{current_user.image_file}')
    transcript = Transcripts.query.filter_by(user_id=current_user.id)
    return render_template('account_transcripts.html', transcripts=transcript, image_file=image_file)

@transcripts.route('/account/transcriptions/<int:id>', methods=['GET', 'POST'])
def transcript(id):
    transcript = Transcripts.query.get_or_404(id)
    user = User.query.get_or_404(transcript.user_id)
    return render_template('transcript.html', transcript=transcript, share=share, user=user)

@transcripts.route('/account/transcriptions/<int:id>/update', methods=['GET', 'POST'])
@login_required
def update_transcript(id):
    transcript = Transcripts.query.get_or_404(id)
    if transcript.user_id != current_user.id:
        abort(403)
    form = SaveWTranscriptionForm()
    if form.validate_on_submit():
        with current_app.app_context():
            transcript.title = form.title.data
            transcript.content = form.content.data
            db.session.commit()
            flash('Your post has been updated!', 'success')
            return redirect(url_for('transcripts.transcript', id=transcript.id))
    elif request.method == 'GET':
        form.title.data = transcript.title
        form.content.data = transcript.content
    return render_template('update_transcript.html', form=form)

@transcripts.route('/account/transcriptions/<int:id>/delete', methods=['POST'])
@login_required
def delete_transcript(id):
    transcript = Transcripts.query.get_or_404(id)
    if transcript.user_id != current_user.id:
        abort(403)
    db.session.delete(transcript)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))



@transcripts.route("/transcriptions/<f_name>", methods=["GET", "POST"])
@login_required
def transcriptions(f_name):
    w_form = SaveWTranscriptionForm()
    d_form = SaveDTranscriptionForm()
    dir_path = os.getcwd()
    deepspeech_transcription_path = f'{dir_path}/deepspeech_transcription/'
    for item in os.listdir(deepspeech_transcription_path):
            if item.endswith('.txt'):
                with open(str(deepspeech_transcription_path + item), 'r') as g:
                    deepspeech_text = g.read()
    whisper_transcription_path = f"{dir_path}/whisper_transcription/"
    for item in os.listdir(whisper_transcription_path):
        if item.endswith('.txt'):
            with open(str(whisper_transcription_path + item), "r") as f:
                whisper_text = f.read()
    if w_form.validate_on_submit():
        with current_app.app_context():
            transcript = Transcripts(title=w_form.title.data,
                                        content=w_form.content.data,
                                        user_id=current_user.id)
            db.session.add(transcript)
            db.session.commit()
            return redirect(url_for('users.account'))
    if d_form.validate_on_submit():
        with current_app.app_context():
            transcript = Transcripts(title=d_form.title.data,
                                        content=d_form.content.data,
                                        user_id=current_user.id)
            db.session.add(transcript)
            db.session.commit()
            return redirect(url_for('users.account'))
    elif request.method == "GET":
        w_form.title.data = f"Whisper: {f_name}"
        d_form.title.data = f"DeepSpeech: {f_name}"
        w_form.content.data = whisper_text
        d_form.content.data = deepspeech_text
    return render_template('transcriptions.html', whisper_form=w_form, deepspeech_form=d_form)

@transcripts.route("/blog")
def blog():
    posts = Post.query.filter_by(user_id=1)
    return render_template('blog.html', posts=posts)

@transcripts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        with current_app.app_context():
            post = Post(title=form.title.data, content=form.content.data, author=current_user)
            db.session.add(post)
            db.session.commit()
            flash('Your post has been created!', 'success')
            return redirect(url_for('transcripts.blog'))
    return render_template('create_post.html', form=form,
                           legend='New Post')

@transcripts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', post=post)

@transcripts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('transcripts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', post=post, 
                           form=form, legend='Update Post')


@transcripts.route('/posts/<int:id>/delete', methods=['POST'])
@login_required
def delete_post(id):
    post = Post.query.get_or_404(id)
    if post.user_id != current_user.id:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('transcripts.blog'))

website/user/routes.py
from flask import (render_template, redirect, url_for, 
                   flash, request, current_app, Blueprint)
from flask_login import login_user, current_user, logout_user, login_required
from website.user.forms import (RegistrationForm, LoginForm, UpdateAccountForm)
from website.models import User, Transcripts
from website import db, bcrypt
from website.user.utils import save_picture

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        with current_app.app_context():
            hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            user = User(username=form.username.data, email=form.email.data, password=hashed_pw)
            db.session.add(user)
            db.session.commit()
            flash(f'Your account has been created! You are now able to log in', 'success')
            return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful. Please check email and password.', 'danger')
    return render_template('login.html', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename=f'profile_pics/{current_user.image_file}')
    transcripts = Transcripts.query.filter_by(user_id=current_user.id)
    return render_template('account.html', image_file=image_file, form=form, transcripts=transcripts)

website/templates/about.html
{% extends 'base.html' %} 

{% block title %}About{% endblock %}

{% block content %} 
    <div class="content-section">
        <h2 class="border-bottom mb-4" align='center'>About</h2>
        <p>This is Transcription Service uses a Python backend running both <a href="https://openai.com/blog/whisper/">Whisper(OpenAI)</a> 
            and <a href="https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwj61_D726v9AhUGS0EAHR1gD2kQFnoECA0QAQ&url=https%3A%2F%2Fgithub.com%2Fmozilla%2FDeepSpeech&usg=AOvVaw3VDjp5wkby9yWiGywOmvWn">DeepSpeech(Mozilla)</a> 
            to transcribe your audio files. Your file is formatted with FFMPEG so it can be correctly handled by each AI transcriber. Once your
            file is in the correct format, it is split into chunks so that it becomes more manageable for the Transcriber AI's to work with. This is done
            simultaneously using <a href="https://www.ray.io">Ray</a> Parallel processing. 
            </p>
        <br>
        <p>Once the file is transcribed by both of the AI's you will be redirected to a form where you can choose a title (default being the 
            file name) and edit the content of the transcription. This is the case as it's not perfect so you may wish to make some adjustments.
            Once you have clicked 'Save', you will be able to view the transcription in your 'Transcriptions' section in your account page.</p>
    </div>

    <div class="content-section">
        <h3>Created by Oli Wood</h3>
        <a href="{{ url_for('transcripts.blog') }}">Features, Future Updates and What I have learned.</a>
        <br>
        <a href="https://github.com/Olijwood/both_transcribers.git">GitHub Repository for this project</a>
    </div>
{% endblock %}

website/templates/account.html
{% extends 'base.html' %} 

{% block title %}Account{% endblock %}

{% block content %} 
    <div class="content-section">
        <div class="media" align="center">
            <img src="{{ image_file }}" class="rounded-circle account-img">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
        <form action="" method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <nav class="navbar border-bottom mb-4">
                    <a href="{{ url_for('users.account') }}" class="nav-item nav-link">Account Info</a>
                    <a href="{{ url_for('transcripts.account_transcripts') }}" class="nav-item nav-link">Your Transcripts</a>
                </nav>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %} 
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %} 
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %} 
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %} 
                </div>
                <br>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %} 
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %} 
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %} 
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %} 
                </div>
                <br>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %} 
                        {% for error in form.picture.errors %} 
                            <span class="text-danger">{{ error }}</span><br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <br>
            <div class="form-group" align="center">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock %}

website/templates/account_transcripts.html
{% extends 'base.html' %} 

{% block title %}Account Transcripts{% endblock %}

{% block content %} 
    <div class="content-section">
        <div class="media" align="center">
            <img src="{{ image_file }}" class="rounded-circle account-img">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
    <nav class="navbar border-bottom mb-4">
        <a href="{{ url_for('users.account') }}" class="nav-item nav-link">Account Info</a>
        <a href="{{ url_for('transcripts.account_transcripts') }}" class="nav-item nav-link">Your Transcripts</a>
    </nav>
    <h3 align="center">Transcripts</h3>
    <div class="transcripts-list">
        {% for transcript in transcripts %} 
            <div class="card">
                <h4><a href="{{ url_for('transcripts.transcript', id=transcript.id) }}">{{ transcript.title }}</a></h4>
                <small><p>{{ transcript.date_created.strftime('%d-%m-%Y') }}</p></small>
            </div>
        {% endfor %}
    </div>
</div>  

    <style>
        .transcripts-list{
            display: grid;
            grid-template-columns: 1fr 1fr;
            grid-gap: 20px;
        }
    </style>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link
        href="https://cdn.jsdelivr.net/npm/shareon@2/dist/shareon.min.css"
        rel="stylesheet"
     />
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <a href="/" class="navbar-brand mr-4">Transcriber</a>
            <button 
                class="navbar-toggler" 
                type="button" 
                data-toggle="collapse" 
                data-target="#navbarSupportedContent"
                >
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item nav-link">
                        <a href="{{ url_for('main.home') }}" class="nav-item nav-link">Home</a>
                    </li>
                    <li class="nav-item nav-link">
                        <a href="{{ url_for('main.about') }}" class="nav-item nav-link">About</a>
                    </li>
                    {% if current_user.is_authenticated %}
                        <li class="nav-item nav-link">
                            <a href="{{ url_for('users.account') }}" class="nav-item nav-link">Account</a>
                        </li>
                        <li class="nav-item nav-link">
                            <a href="{{ url_for('users.logout') }}" class="nav-item nav-link">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item nav-link">
                            <a href="{{ url_for('users.login') }}" class="nav-item nav-link">Login</a>
                        </li>
                        <li class="nav-item nav-link">
                            <a href="{{ url_for('users.register') }}" class="nav-item nav-link">Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/shareon@2/dist/shareon.iife.js" defer init></script>
</body>
</html>

website/templates/blog.html
{% extends 'base.html' %} 

{% block title %}Blog{% endblock title %}

{% block content %} 
    {% if current_user.id == 1 %}
    <a href="{{ url_for('transcripts.new_post') }}">Create Post</a>
    {% endif %}
    {% for post in posts %} 
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" alt="">
            <div class="media-body">
                <div class="article-metadata">
                    <p class="mr-2">{{ post.author.username }}</p>
                    <small class="text-muted">{{ post.date_posted.strftime('%d-%m-%Y') }}</small>
                </div>
                <h2><a href="{{ url_for('transcripts.post', post_id=post.id) }}" class="article-title">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock content %} 

website/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %} 
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %} 
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %} 
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %} 
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %} 
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %} 
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %} 
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %} 
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input")}}
                    {{ form.remember.label(class="form-check-label")}}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Don't have an account? <a href="{{ url_for('users.register') }}" class="ml-2">Sign Up Now</a>
        </small>
    </div>
{% endblock %}

website/templates/post.html
{% extends 'base.html' %} 

{% block title %}Blog{% endblock title %}

{% block content %} 
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" alt="">
            <div class="media-body">
                <div class="article-metadata">
                    <p class="mr-2">{{ post.author.username }}</p>
                    <small class="text-muted">{{ post.date_posted.strftime('%d-%m-%Y') }}</small>
                    {% if post.author == current_user %}
                        <div>
                            <a href="{{ url_for('transcripts.update_post', post_id=post.id) }}" class="btn btn-secondary btn-sm m-1">Update</a>
                            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModalCenter">Delete</button>
                        </div>
                    {% endif %}
                </div>
                <h2 class="article-title">{{ post.title }}</h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
        <div class="modal fade" id="deleteModalCenter" tabindex="-1" role="dialog" aria-labelledby="deleteModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="deleteModalLongTitle">Delete Post?</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <form action="{{ url_for('transcripts.delete_post', id=post.id) }}" method="POST">
                    <input type="submit" class="btn btn-danger" value="Delete">
                  </form>
                </div>
              </div>
            </div>
        </div>
{% endblock content %} 

website/templates/transcript.html
{% extends 'base.html' %}

{% block title %}{{ transcript.title }}{% endblock title %}
<head>{{ share.load() }}</head>
{% block content %} 
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata" align="center">
                {% if transcript.user_id == current_user.id %} 
                    <a href="{{ url_for('transcripts.update_transcript', id=transcript.id) }}" class="btn btn-secondary btn-sm mt-1 mb-1" >Edit</a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModalCenter">Delete</button>
                {% endif %}
                <h4 align="center">Share with: </h4>
                <div class="shareon" align="center">
                    <a class="facebook"></a>
                    <a class="linkedin"></a>
                    <a class="messenger" data-fb-app-id="FACEBOOK APP IDD"></a>
                    <a class="pinterest"></a>
                    <button class="reddit"></button>
                    <button class="telegram"></button>
                    <button class="twitter"></button>
                    <button class="whatsapp"></button>
                </div>
            </div>
            <h2 class="article-title">{{ transcript.title }}</h2>
            <small><h5 class="text-muted">{{ user.username }}</h5></small>
            <small><p class="text-muted">{{ transcript.date_created.strftime('%d-%m-%Y') }}</p></small>
            <p class="article-content">{{ transcript.content }}</p>
        </div>
    </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModalCenter" tabindex="-1" role="dialog" aria-labelledby="deleteModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLongTitle">Delete Transcript?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <form action="{{ url_for('transcripts.delete_transcript', id=transcript.id) }}" method="POST">
                <input type="submit" class="btn btn-danger" value="Delete">
              </form>
            </div>
          </div>
        </div>
    </div>
{% endblock content %}